file_upload_check:
    pattern:  /check
    defaults: { _controller: KitpagesFileBundle:Upload:check }
    
file_upload_do_upload:
    pattern:  /upload
    defaults: { _controller: KitpagesFileBundle:Upload:doUpload }
