file_upload_check:
    pattern:  /check
    defaults: { _controller: KitpagesFileBundle:Upload:check }
    
file_upload_do_upload:
    pattern:  /do-upload
    defaults: { _controller: KitpagesFileBundle:Upload:doUpload }

file_upload_upload:
    pattern:  /upload
    defaults: { _controller: KitpagesFileBundle:Upload:upload }
    
kitpages_file_render:
    pattern:  /render
    defaults: { _controller: KitpagesFileBundle:Render:view }    
