file_upload_check:
    pattern:  /check
    defaults: { _controller: KitpagesFileBundle:Upload:check }

file_upload_do_upload:
    pattern:  /do-upload/{entityFileName}
    defaults: { _controller: KitpagesFileBundle:Upload:doUpload }

kitpages_file_render:
    pattern:  /render/{entityFileName}
    defaults: { _controller: KitpagesFileBundle:Render:view, entityFileName:default }

kitpages_file_info:
    pattern:  /info/{entityFileName}
    defaults: { _controller: KitpagesFileBundle:Render:info }
###
# Action list
###

kitpages_file_actionOnFile_widgetEmpty:
    pattern:  /noAction
    defaults: { _controller: KitpagesFileBundle:ActionOnFile:widgetEmpty }
# default
kitpages_file_actionOnFile_widget:
    pattern:  /fileAction/{typeFile}/{actionFile}
    defaults: { _controller: KitpagesFileBundle:ActionOnFile:widget }

kitpages_file_actionOnFile_do:
    pattern:  /doAction/{typeFile}/{actionFile}
    defaults: { _controller: KitpagesFileBundle:ActionOnFile:do }

kitpages_file_actionOnFile_widgetResizeImage:
    pattern:  /resizeImage
    defaults: { _controller: KitpagesFileBundle:ActionOnFile:widgetResizeImage }

kitpages_file_actionOnFile_doResizeImage:
    pattern:  /doResizeImage
    defaults: { _controller: KitpagesFileBundle:ActionOnFile:doResizeImage }

kitpages_file_actionOnFile_widgetCropImage:
    pattern:  /cropImage
    defaults: { _controller: KitpagesFileBundle:ActionOnFile:widgetCropImage }
